export const bookAbbreviations: { [key: string]: string } = {
    'Gênesis': 'Gn',
    'Êxodo': 'Ex',
    'Levítico': 'Lv',
    'Números': 'Nm',
    'Deuteronômio': 'Dt',
    'Josué': 'Js',
    'Juízes': 'Jz',
    'Rute': 'Rt',
    '1 Samuel': '1Sm',
    '2 Samuel': '2Sm',
    '1 Reis': '1Rs',
    '2 Reis': '2Rs',
    '1 Crônicas': '1Cr',
    '2 Crônicas': '2Cr',
    'Esdras': 'Esd',
    'Neemias': 'Ne',
    'Tobias': 'Tb',
    'Judite': 'Jt',
    'Ester': 'Est',
    '1 Macabeus': '1Mc',
    '2 Macabeus': '2Mc',
    'Jó': 'Jó',
    'Salmos': 'Sl',
    'Provérbios': 'Pr',
    'Eclesiastes': 'Ecl',
    'Cântico dos Cânticos': 'Ct',
    'Sabedoria': 'Sb',
    'Eclesiástico': 'Eclo',
    'Isaías': 'Is',
    'Jeremias': 'Jr',
    'Lamentações': 'Lm',
    'Baruc': 'Br',
    'Ezequiel': 'Ez',
    'Daniel': 'Dn',
    'Oseias': 'Os',
    'Joel': 'Jl',
    'Amós': 'Am',
    'Abdias': 'Ab',
    'Jonas': 'Jn',
    'Miquéias': 'Mq',
    'Naum': 'Na',
    'Habacuque': 'Hab',
    'Sofonias': 'Sf',
    'Ageu': 'Ag',
    'Zacarias': 'Zc',
    'Malaquias': 'Ml',
    'Mateus': 'Mt',
    'Marcos': 'Mc',
    'Lucas': 'Lc',
    'João': 'Jo',
    'Atos dos Apóstolos': 'At',
    'Romanos': 'Rm',
    '1 Coríntios': '1Cor',
    '2 Coríntios': '2Cor',
    'Gálatas': 'Gl',
    'Efésios': 'Ef',
    'Filipenses': 'Fl',
    'Colossenses': 'Cl',
    '1 Tessalonicenses': '1Ts',
    '2 Tessalonicenses': '2Ts',
    '1 Timóteo': '1Tm',
    '2 Timóteo': '2Tm',
    'Tito': 'Tt',
    'Filemon': 'Fm',
    'Hebreus': 'Hb',
    'Tiago': 'Tg',
    '1 Pedro': '1Pd',
    '2 Pedro': '2Pd',
    '1 João': '1Jo',
    '2 João': '2Jo',
    '3 João': '3Jo',
    'Judas': 'Jd',
    'Apocalipse': 'Ap',
    'primeira carta de são paulo aos coríntios': '1Cor',
    'segunda carta de são paulo aos coríntios': '2Cor',
    'primeira carta de são paulo a timóteo': '1Tm',
    'segunda carta de são paulo a timóteo': '2Tm',
    'carta de são paulo a tito': 'Tt',
    'carta de são paulo a filêmon': 'Fm',
    'carta de são paulo aos romanos': 'Rm',
    'carta de são paulo aos efésios': 'Ef',
    'carta de são paulo aos filipenses': 'Fl',
    'carta de são paulo aos colossenses': 'Cl',
    'primeira carta de são paulo aos tessalonicenses': '1Ts',
    'segunda carta de são paulo aos tessalonicenses': '2Ts',
    'carta de são tiago': 'Tg',
    'primeira carta de são pedro': '1Pd',
    'segunda carta de são pedro': '2Pd',
    'primeira carta de são joão': '1Jo',
    'segunda carta de são joão': '2Jo',
    'terceira carta de são joão': '3Jo',
    'carta de são judas': 'Jd',
    'atos dos apóstolos': 'At',
    'apocalipse de são joão': 'Ap',
    'evangelho de são mateus': 'Mt',
    'evangelho de são marcos': 'Mc',
    'evangelho de são lucas': 'Lc',
    'evangelho de são joão': 'Jo'
}